version: '3'
services:
  mytgbot:
    build: .
    container_name: nocktgbot
    ports:
      - "3000:3000"
    env_file:
      - .env
  fastapi:
    build:
      context: ./fastapi_app
    ports:
      - "3050:3050"
