version: '3.8'

services:
  mytgbot:
    build:
      context: .
    container_name: nocktgbot
    command: python /app/bot/main.py
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    env_file:
      - .env

  fastapi:
    build:
      context: .
    container_name: fastapi
    command: uvicorn fastapi_app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - "3050:8000"
    env_file:
      - .env
